contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact-us/', views.contact_us, name='contact_us'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('/blog', views.blog, name='blog'),
    path('/about', views.about, name='about')

]

properties/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sell/', views.sell, name='sell'),
    path('luxury-estate/', views.luxury_estate, name='luxury_estate'),
    path('oceanfront-retreats/', views.oceanfront_retreats, name='oceanfront_retreats'),
    path('urban-living/', views.urban_living, name='urban_living'),
    path('countryside_escapes/', views.countryside_escapes, name='countryside_escapes'),
    path('property-search/', views.property_search, name='property_search'),

]

re01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('properties/', include('properties.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/',views.register,name='register'),
    path('logout/', views.logout_view, name='logout'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    property_id = models.BigIntegerField(blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name

core/models.py
from django.db import models

# Create your models here.

properties/models.py
from django.db import models


# Define choices for property categories
PROPERTY_CATEGORIES = (
    ('luxury', 'Luxury Estate'),
    ('oceanfront', 'Oceanfront Retreats'),
    ('urban', 'Urban Living Gems'),
    ('countryside', 'Countryside Escapes'),
)


class Property(models.Model):
    id = models.AutoField(blank=False, primary_key=True)
    property_title = models.CharField(max_length=200)
    property_description = models.TextField()
    property_type = models.CharField(max_length=50)
    property_category = models.CharField(max_length=20, choices=PROPERTY_CATEGORIES, default='luxury')
    property_price = models.DecimalField(max_digits=10, decimal_places=2)
    property_location = models.CharField(max_length=100)
    property_features = models.TextField(blank=True, null=True)
    seller_name = models.CharField(max_length=100)
    seller_email = models.EmailField()
    seller_phone = models.CharField(max_length=15)
    property_images = models.ImageField(upload_to='property_images/', blank=True, null=True)

    def __str__(self):
        return self.property_title

users/models.py
from django.db import models


# Create your models here.
class Userregistration(models.Model):
    id=models.AutoField(blank=False,primary_key=True)
    username = models.CharField(max_length=50,blank=False)
    email = models.EmailField(max_length=50,blank=False)
    password = models.CharField(max_length=20)
    repassword = models.CharField(max_length=20)

    def __str__(self):
        return self.username

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email',  'property_id', 'message']

properties/forms.py
from django import forms
from .models import Property


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        field = "__all__"
        exclude = ["id"]

users/forms.py
from django import forms
from .models import Userregistration


class UserRegForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    repassword = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Userregistration
        fields = ['username', 'email', 'password', 'repassword']

contact/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import ContactForm



def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            # You can add a success message or redirect to a thank-you page here
            return render(request, 'contact/thank.html')
    else:
        form = ContactForm()

    return render(request, 'contact/contact_us.html', {'form': form})

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.

def homepage(request):
    return render(request, 'core/index.html')


def blog(request):
    return render(request, 'core/blog.html')



def about(request):
    return render(request, 'core/about.html')

properties/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Property
from .forms import PropertyForm
from django.db.models import Q



def sell(request):
    form = PropertyForm(request.POST, request.FILES)
    if request.method == "POST":

        print('inside post')
        if form.is_valid():
            form.save()
            return render(request, 'properties/success.html')
    # else:
    #     form = UserRegForm()
    return render(request, 'properties/sell.html', {'form': form})



def luxury_estate(request):
    properties = Property.objects.filter(property_category='luxury')
    return render(request, 'properties/property_list.html', {'properties': properties})



def oceanfront_retreats(request):
    properties = Property.objects.filter(property_category='oceanfront')
    return render(request, 'properties/property_list.html', {'properties': properties})


def urban_living(request):
    properties = Property.objects.filter(property_category='urban')
    return render(request, 'properties/property_list.html', {'properties': properties})


def countryside_escapes(request):
    properties = Property.objects.filter(property_category='countryside')
    return render(request, 'properties/property_list.html', {'properties': properties})


def property_search(request):
    search_query = request.GET.get('search_query', '')
    location_filter = request.GET.get('location', '')
    category_filter = request.GET.get('category', '')
    features_filter = request.GET.get('features', '')

    # Use Q objects to perform an OR search across multiple fields
    properties = Property.objects.filter(
        Q(property_title__icontains=search_query) |
        Q(property_location__icontains=search_query) |
        Q(property_category__icontains=search_query) |
        Q(property_features__icontains=search_query)
    )

    return render(request, 'properties/search_results.html', {'properties': properties, 'search_query': search_query})

users/views.py
from django.db.models import Q
from django.db.models.sql import AND
from django.shortcuts import render
from .models import Userregistration
from .forms import UserRegForm
from django.contrib.auth import logout
from django.shortcuts import redirect


def login_page(request):
    context = {'message': 'Invalid Credentials......'}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        data = Userregistration.objects.filter(Q(username=username), Q(password=password))
        if data:
            return render(request, 'core/index.html')
        else:
            return render(request, 'users/login_page.html', context)
    return render(request, 'users/login_page.html')


def register(request):
    form = UserRegForm(request.POST)
    if request.method == "POST":

        print('inside post')
        if form.is_valid():
            form.save()
            return render(request, 'core/index.html')
    # else:
    #     form = UserRegForm()
    return render(request, 'users/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('homepage')  # Redirect to your desired page after logout

contact/templates/contact/contact_us.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="max-width: 400px; margin: 50px auto 20px auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2); background-color: #fff; text-align: center;">

    <h1> Contact Us </h1>

    <form method="POST" style="margin-top: 20px; display: inline-block; text-align: left;">

        {% csrf_token %}

        <div style="text-align: left;">
            <label for="id_name" style="font-weight: bold;">Name:</label><br>
            {{ form.name }}
            <br>

            <label for="id_email" style="font-weight: bold;">Email:</label><br>
            {{ form.email }}
            <br>
            <label for="" style="font-weight: bold;">Property ID (optional):</label><br>
            {{ form.property_id }}
            <br>

            <label for="id_message" style="font-weight: bold;">Message:</label><br>
            {{ form.message }}
            <br>

        </div>

        <div style="text-align: center;">
            <input type="submit" value="Submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; margin-top: 20px;">
        </div>

    </form>

</div>
{% endblock %}

contact/templates/contact/thank.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="display: flex; justify-content: center; min-height: 100vh;">
  <div style="background-color: #f2f2f2; padding: 20px; border: 1px solid #ccc; border-radius: 5px; text-align: center; max-width: 400px; max-height: 300px; margin-top: 40px;">
    <p><b>Thank you for reaching out to us! </b><br> Your inquiry has been successfully received. One of our dedicated agents will review your message and get back to you as soon as possible. We appreciate your interest in our services and look forward to assisting you. In the meantime, feel free to explore our website for more information about our offerings.</p>
  </div>
</div>
{% endblock %}

core/templates/core/TermsAndConditions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TremsToFollow</title>
    <p>
        **Terms and Conditions**

Welcome to [Your Company Name]! These terms and conditions outline the rules and regulations for the use of [Your Company Name]'s Website and Services, located at [Your Website URL].

By accessing this website or using our services, we assume you accept these terms and conditions. Do not continue to use [Your Company Name] if you do not agree to take allof the terms and conditions stated on this page.

The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company’s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance, and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services, in accordance with and subject to, prevailing law of [Your Country]. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to the same.

**Cookies**

We employ the use of cookies. By accessing [Your Company Name], you agreed to use cookies in agreement with the [Your Company Name]'s Privacy Policy.

Most interactive websites use cookies to let us retrieve the user’s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.

**License**

Unless otherwise stated, [Your Company Name] and/or its licensors own the intellectual property rights for all material on [Your Company Name]. All intellectual property rights are reserved. You may access this from [Your Company Name] for your own personal use subjected to restrictions set in these terms and conditions.

You must not:

- Republish material from [Your Company Name]
- Sell, rent, or Sub-license material from [Your Company Name]
- Reproduce, duplicate or copy material from [Your Company Name]
- Redistribute content from [Your Company Name]

This Agreement shall begin on the date hereof.

Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. [Your Company Name] does not filter, edit, publish, or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of [Your Company Name],its agents, and/or affiliates. Comments reflect the views and opinions of the person who posts their views and opinions. To the extent permitted by applicable laws, [Your Company Name] shall not be liable for the Comments or for any liability, damages, or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.

[Your Company Name] reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive, or causes breach of these Terms and Conditions.

You warrant and represent that:

- You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;
- The Comments do not invade any intellectual property right, including without limitation copyright, patent, or trademark of any third party;
- The Comments do not contain any defamatory, libelous, offensive, indecent, or otherwise unlawful material which is an invasion of privacy
- The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.

You hereby grant [Your Company Name] a non-exclusive license to use, reproduce, edit, and authorize others to use, reproduce, and edit any of your Comments in any and all forms, formats, or media.

**Hyperlinking to our Content**

The following organizations may link to our Website without prior written approval:

- Government agencies;
- Search engines;
- News organizations;
- Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and
- Systemwide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Website.

These organizations may link to our home page, to publications, or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement, or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party’s site.

We may consider and approve other link requests from the following types of organizations:

- commonly-known consumer and/or business information sources;
- dot.com community sites;
- associations or other groups representing charities;
- online directory distributors;
- internet portals;
- accounting, law, and consulting firms; and
- educational institutions and trade associations.

We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of [Your Company Name]; and (d) the link is in the context of general resource information.

These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement, or approval of the linking party and its products or services; and (c) fits within the context of the linking party’s site.

If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to [Your Company Name]. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.

Approved organizations may hyperlink to our Website as follows:

- By use of our corporate name; or
- By use of the uniform resource locator being linked to; or
- By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party’s site.

No use of [Your Company Name]'s logo or other artwork will be allowed for linking absent a trademark license agreement.

**iFrames**

Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.

**Content Liability**

We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that are rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene, or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.

**Reservation of Rights**

We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right
    </p>
</head>
<body>

</body>
</html>

core/templates/core/about.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
 <header class="bg-primary text-light py-5">
        <div class="container text-center">
            <h1 class="display-4">About Us</h1>
        </div>
    </header>

    <main class="container my-5">
        <section>
            <h2>Our Story</h2>
            <p>
                Welcome to Your Real Estate Company, where we turn your property dreams into reality. Founded in 20XX, we have been dedicated to providing top-notch real estate services
                to our valued clients for over a decade.
            </p>
cd             <p>
                Our journey started with a vision: to create a modern and innovative real estate agency that offers personalized solutions to meet the unique needs of each client. Today,
                that vision is a reality.
            </p>
        </section>

        <section class="mt-5">
            <h2>Our Mission</h2>
            <p>
                At Your Real Estate Company, our mission is simple yet powerful: to help you find your perfect home or investment property while ensuring a smooth and stress-free
                experience. We are committed to delivering exceptional service, honest advice, and expert guidance throughout your real estate journey.
            </p>
            <p>
                Whether you are buying, selling, renting, or investing, our team of dedicated professionals is here to support you every step of the way. Your satisfaction is our ultimate
                goal, and we take pride in exceeding your expectations.
            </p>
        </section>
    </main>
{% endblock %}

core/templates/core/base.html
{% load static %}
 <!-- Add this line to load user context -->
<html>
<html lang="en">
<head>
    <title>World's best real estate solution</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid px-5">
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/lease.gif' %}" alt="logo" style="width: 50px; height: 50px; display: inline-block;">
                <h1 style="font-family: 'Pacifico', cursive; font-size: 32px; display: inline-block;">SRI AGASTYA</h1>
            </a>
            <form class="d-flex justify-content-center mx-2" action="{% url 'property_search' %}" method="GET">
    <input class="form-control me-2" type="text" name="search_query"
           placeholder="Search by Location, Category, Features..." aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>


            <!-- ... (previous HTML code) ... -->

<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="signInDropdown" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            <img
                src="https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/images/profile-815786.svg"
                alt="Sign in" class="-dOa_b L_FVxe" width="24" height="24">
            {% if user.is_authenticated %}
                <span class="_1sLnDu">Logout</span>
            {% else %}
                <span class="_1sLnDu">Sign in</span>
            {% endif %}
        </a>
        <ul class="dropdown-menu" aria-labelledby="signInDropdown">
            {% if user.is_authenticated %}
                <li>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li>
                    <a class="dropdown-item" href="{% url 'register' %}">New Customer? Sign Up</a>
                </li>
                <li>
                    <a class="dropdown-item text-dark" href="{% url 'login' %}">My Profile</a>
                </li>
            {% endif %}
        </ul>
    </li>

<!-- ... (remaining HTML code) ... -->

            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav w-100 d-flex flex-row justify-content-around">
                    <li class="nav-item flex-fill">
                        <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown flex-fill">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Explore
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Explore dropdown items -->
                            <li><a class="dropdown-item" href="{% url 'homepage' %}#Features">Buy</a></li>
                            <li><a class="dropdown-item" href="{% url 'homepage' %}#Features">Rent</a></li>
                            <li><a class="dropdown-item" href="{% url 'sell' %}">Sell</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown flex-fill">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Featured
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Featured dropdown items -->
                            <li><a class="dropdown-item" href="{% url 'luxury_estate' %}">Luxury Estates</a></li>
                            <li><a class="dropdown-item" href="{% url 'oceanfront_retreats' %}">Oceanfront Retreats</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'urban_living' %}">Urban Living Gems</a></li>
                            <li><a class="dropdown-item" href="{% url 'countryside_escapes' %}">Countryside Escapes</a>
                            </li>
                            <li><a class="dropdown-item" href="#">Investment Opportunities</a></li>
                            <li><a class="dropdown-item" href="#">Unique Architecture</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown flex-fill">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Services
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Services dropdown items -->
                            <li><a class="dropdown-item" href="#">Property Insights</a></li>
                            <li><a class="dropdown-item" href="#">Personalized Consultations</a></li>
                            <li><a class="dropdown-item" href="#">Virtual Tours</a></li>
                            <li><a class="dropdown-item" href="#">Home Staging & Design</a></li>
                            <li><a class="dropdown-item" href="#">Property Management</a></li>
                            <li><a class="dropdown-item" href="#">Investment Analysis</a></li>
                            <li><a class="dropdown-item" href="#">Sustainable Living</a></li>
                        </ul>
                    </li>
                    <li class="nav-item flex-fill">
                        <a class="nav-link" href="{% url 'blog' %}">Blog</a>
                    </li>
                    <li class="nav-item flex-fill">
                        <a class="nav-link" href="{% url 'contact_us' %}">Contact</a>
                    </li>
                    <li class="nav-item flex-fill">
                        <a class="nav-link" href="#">
                            <img src="{% static 'images/bookmark.png' %}" alt="Icon Bookmark" width="20" height="20"
                                 class="d-inline-block align-text-top">
                            Saved Properties
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
<footer class="py-3">
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                </a>
                <span class="text-muted">© 2024 SRI AGASTYA, Inc</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'images/twitter.png' %}"
                                                                     alt="Icon Bookmark" width="20" height="20"
                                                                     class="d-inline-block align-text-top"></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'images/instagram.png' %}"
                                                                     alt="Icon Bookmark" width="20" height="20"
                                                                     class="d-inline-block align-text-top"></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'images/facebook.png' %}"
                                                                     alt="Icon Bookmark" width="20" height="20"
                                                                     class="d-inline-block align-text-top"></a></li>
            </ul>
        </footer>
    </div>
</footer>
</body>
</html>

properties/templates/properties/success.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<h1 style="text-align:center;">Added to list.</h1>
{% endblock %}

users/templates/users/loginsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Login Success</h1>
</body>
</html>

users/templates/users/register.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="max-width: 400px; margin: 50px auto 20px auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2); background-color: #fff; text-align: center;">

    <h1> SIGN UP</h1>

    <form method="POST" style="margin-top: 20px; display: inline-block; text-align: left;">

        {% csrf_token %}

        <div style="text-align: left;">
            <label for="id_username" style="font-weight: bold;">Username:</label><br>
            {{ form.username }}
            <br>

            <label for="id_email" style="font-weight: bold;">Email:</label><br>
            {{ form.email }}
            <br>

            <label for="id_password" style="font-weight: bold;">Password:</label><br>
            {{ form.password }}
            <br>

            <label for="id_repassword" style="font-weight: bold;">Confirm Password:</label><br>
            {{ form.repassword }}
            <br>
        </div>

        <div style="text-align: center;">
            <input type="submit" value="Submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; margin-top: 20px;">
        </div>

    </form>

</div>
{% endblock %}

users/templates/users/regsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>User Registered Success</h1>
<button><a href="{% url 'login' %}">Login</a></button>
</body>
</html>